<a href="https://colab.research.google.com/github/thevindusubasinha/bug-free-invention/blob/main/F1%20threshold%20measure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd

# Define file path
file_path = '/content/sample_data/actaruslab_f1_telemetry_2026.csv'

# Load the dataset
df = pd.read_csv(file_path)

# Sort the table by speed_kmh in ascending order
df_sorted_asc = df.sort_values(by='speed_kmh', ascending=True).reset_index(drop=True)

# Save the rearranged table back to the CSV file
df_sorted_asc.to_csv(file_path, index=False)

# Display all the rows of the sorted table
display(df_sorted_asc.head(150001))

,speed_kmh,wing_angle_deg,drs_active,downforce_n,drag_n,stability_index
0,100.00,28.50,1,563.86,25.80,100.0
1,100.00,6.68,0,137.42,24.27,100.0
2,100.00,30.86,1,606.03,27.05,100.0
3,100.00,21.19,0,427.06,29.81,100.0
4,100.00,23.58,0,472.62,31.19,100.0
...,...,...,...,...,...,...
149995,364.99,31.91,0,8318.92,490.67,0.0
149996,364.99,24.76,0,6591.30,425.21,0.0
149997,364.99,32.52,0,8462.64,496.80,0.0
149998,365.00,6.69,0,1834.62,323.36,100.0
149999,365.00,5.44,0,1492.26,320.47,100.0

In [34]:
import pandas as pd

# Assuming df_sorted_asc is already loaded and sorted from the previous cell
# Create a comparison table for speed and drag
comparison_df = df_sorted_asc[['speed_kmh', 'drag_n']]

# Display the comparison table
print("Comparison: Speed vs Drag")
display(comparison_df.head(50))

Comparison: Speed vs Drag

    speed_kmh  drag_n
0      100.00   25.80
1      100.00   24.27
2      100.00   27.05
3      100.00   29.81
4      100.00   31.19
5      100.01   28.51
6      100.01   24.12
7      100.01   21.54
8      100.01   25.85
9      100.01   30.71
10     100.01   28.27
11     100.01   37.91
12     100.01   26.79
13     100.02   31.46
14     100.02   18.19
15     100.02   26.38
16     100.02   21.17
17     100.02   28.91
18     100.03   30.76
19     100.03   25.10
20     100.03   24.03
21     100.03   24.62
22     100.03   18.52
23     100.03   25.02
24     100.03   36.07
25     100.03   36.92
26     100.03   24.47
27     100.03   28.76
28     100.03   21.57
29     100.04   28.09
30     100.04   28.34
31     100.04   25.37
32     100.04   30.43
33     100.04   21.66
34     100.04   27.67
35     100.05   30.70
36     100.05   24.43
37     100.05   25.63
38     100.05   25.71
39     100.05   27.93
40     100.05   24.78
41     100.06   19.36
42     100.06   26.83
43     100.06   24.15
44     100.06   25.16
45     100.06   28.71
46     100.06   21.34
47     100.06   33.10
48     100.06   19.08
49     100.07   26.29

In [35]:
# Display the last 50 rows of the comparison table
print("Comparison: Speed vs Drag (Last 50 Rows)")
display(comparison_df.tail(50))

Comparison: Speed vs Drag (Last 50 Rows)

        speed_kmh  drag_n
149950     364.91  366.07
149951     364.91  374.99
149952     364.92  375.86
149953     364.92  386.89
149954     364.92  504.03
149955     364.92  454.34
149956     364.92  340.41
149957     364.92  477.17
149958     364.93  416.58
149959     364.93  347.23
149960     364.93  337.42
149961     364.93  330.32
149962     364.93  378.06
149963     364.93  338.48
149964     364.94  275.27
149965     364.94  317.04
149966     364.94  402.35
149967     364.94  342.82
149968     364.94  344.36
149969     364.94  365.90
149970     364.94  373.24
149971     364.94  379.05
149972     364.95  335.17
149973     364.95  449.83
149974     364.95  464.94
149975     364.95  517.94
149976     364.95  474.55
149977     364.95  244.05
149978     364.96  386.51
149979     364.96  425.79
149980     364.96  269.88
149981     364.96  345.71
149982     364.96  445.93
149983     364.96  351.97
149984     364.96  323.84
149985     364.96  503.18
149986     364.97  326.78
149987     364.97  391.41
149988     364.97  364.20
149989     364.97  325.30
149990     364.98  363.51
149991     364.98  325.16
149992     364.98  249.10
149993     364.98  247.63
149994     364.98  335.78
149995     364.99  490.67
149996     364.99  425.21
149997     364.99  496.80
149998     365.00  323.36
149999     365.00  320.47

In [36]:
import plotly.express as px

# Creating an interactive scatter plot using a subset of data for better performance
# If the dataset is very large (150k rows), we take a sample to keep the chart responsive
fig = px.scatter(df_sorted_asc.sample(n=min(10000, len(df_sorted_asc))),
                 x='speed_kmh',
                 y='drag_n',
                 title='Interactive Chart: Drag vs Speed',
                 labels={'speed_kmh': 'Speed (km/h)', 'drag_n': 'Drag (N)'},
                 opacity=0.5)

fig.update_traces(marker=dict(size=5))
fig.show()

In [37]:
# Create a comparison table for speed and stability index
stability_df = df_sorted_asc[['speed_kmh', 'stability_index']]

# Display the top 50 rows
print("Comparison: Speed vs Stability Index (First 50 Rows)")
display(stability_df.head(50))

Comparison: Speed vs Stability Index (First 50 Rows)

    speed_kmh  stability_index
0      100.00            100.0
1      100.00            100.0
2      100.00            100.0
3      100.00            100.0
4      100.00            100.0
5      100.01            100.0
6      100.01            100.0
7      100.01            100.0
8      100.01            100.0
9      100.01            100.0
10     100.01            100.0
11     100.01            100.0
12     100.01            100.0
13     100.02            100.0
14     100.02            100.0
15     100.02            100.0
16     100.02            100.0
17     100.02            100.0
18     100.03            100.0
19     100.03            100.0
20     100.03            100.0
21     100.03            100.0
22     100.03            100.0
23     100.03            100.0
24     100.03            100.0
25     100.03            100.0
26     100.03            100.0
27     100.03            100.0
28     100.03            100.0
29     100.04            100.0
30     100.04            100.0
31     100.04            100.0
32     100.04            100.0
33     100.04            100.0
34     100.04            100.0
35     100.05            100.0
36     100.05            100.0
37     100.05            100.0
38     100.05            100.0
39     100.05            100.0
40     100.05            100.0
41     100.06            100.0
42     100.06            100.0
43     100.06            100.0
44     100.06            100.0
45     100.06            100.0
46     100.06            100.0
47     100.06            100.0
48     100.06            100.0
49     100.07            100.0

In [38]:
# Display the last 50 rows of the stability comparison table
print("Comparison: Speed vs Stability Index (Last 50 Rows)")
display(stability_df.tail(50))

Comparison: Speed vs Stability Index (Last 50 Rows)

        speed_kmh  stability_index
149950     364.91           100.00
149951     364.91            81.42
149952     364.92            79.72
149953     364.92            58.51
149954     364.92             0.00
149955     364.92             0.00
149956     364.92           100.00
149957     364.92             0.00
149958     364.93             8.46
149959     364.93           100.00
149960     364.93           100.00
149961     364.93             0.00
149962     364.93             0.00
149963     364.93             0.00
149964     364.94            98.16
149965     364.94             0.00
149966     364.94            31.42
149967     364.94           100.00
149968     364.94           100.00
149969     364.94           100.00
149970     364.94             0.00
149971     364.94            73.45
149972     364.95           100.00
149973     364.95             0.00
149974     364.95             0.00
149975     364.95             0.00
149976     364.95             0.00
149977     364.95           100.00
149978     364.96            59.33
149979     364.96             0.00
149980     364.96           100.00
149981     364.96           100.00
149982     364.96             0.00
149983     364.96           100.00
149984     364.96           100.00
149985     364.96             0.00
149986     364.97           100.00
149987     364.97            50.41
149988     364.97           100.00
149989     364.97           100.00
149990     364.98           100.00
149991     364.98           100.00
149992     364.98           100.00
149993     364.98           100.00
149994     364.98           100.00
149995     364.99             0.00
149996     364.99             0.00
149997     364.99             0.00
149998     365.00           100.00
149999     365.00           100.00

In [39]:
import plotly.express as px

# Filter the last 100 rows
last_50 = df_sorted_asc.tail(100)

# Create a scatter plot for downforce vs wing angle
fig = px.scatter(last_50,
                 x='wing_angle_deg',
                 y='downforce_n',
                 color='stability_index',
                 title='Last 50 Rows: Downforce vs Wing Angle (Colored by Stability)',
                 labels={'wing_angle_deg': 'Wing Angle (deg)', 'downforce_n': 'Downforce (N)'})

fig.show()

In [40]:
import plotly.express as px

# Filter the last 100 rows
last_50 = df_sorted_asc.head(100)

# Create a scatter plot for downforce vs wing angle
fig = px.scatter(last_50,
                 x='wing_angle_deg',
                 y='downforce_n',
                 color='stability_index',
                 title='first 50 Rows: Downforce vs Wing Angle (Colored by Stability)',
                 labels={'wing_angle_deg': 'Wing Angle (deg)', 'downforce_n': 'Downforce (N)'})

fig.show()

In [41]:
#as the angle of the wing increases the downforce increases

In [42]:
import plotly.express as px

# Create an interactive scatter plot for stability index vs downforce
# Sampling for performance if needed, but plotting enough to see the trend
fig = px.scatter(df_sorted_asc.sample(n=min(20000, len(df_sorted_asc))),
                 x='downforce_n',
                 y='stability_index',
                 color='speed_kmh',
                 title='Stability Index vs Downforce (Colored by Speed)',
                 labels={'downforce_n': 'Downforce (N)', 'stability_index': 'Stability Index'},
                 opacity=0.4)

fig.show()

In [43]:
#after the downforce exceeds the 6510N it makes the stability 0

In [44]:
# Find the first row where stability_index is less than 100
first_instability = df_sorted_asc[df_sorted_asc['stability_index'] < 100].head(1)

print("The exact moment stability becomes less than 100 (in ascending order):")
display(first_instability)

The exact moment stability becomes less than 100 (in ascending order):

,speed_kmh,wing_angle_deg,drs_active,downforce_n,drag_n,stability_index
89518,258.3,34.85,1,4504.3,195.46,99.78

In [45]:
#at this exact point when the downforce becomes 4504.3 N, the stability of the car drops feom the perfect 100. that means the downforce is the main factor that contribute to the lose of the stability

In [46]:
import plotly.express as px

# Create an interactive scatter plot for drag vs speed
fig = px.scatter(df_sorted_asc.sample(n=min(15000, len(df_sorted_asc))),
                 x='speed_kmh',
                 y='drag_n',
                 color='wing_angle_deg',
                 title='Drag (N) vs Speed (km/h) - Colored by Wing Angle',
                 labels={'speed_kmh': 'Speed (km/h)', 'drag_n': 'Drag (N)', 'wing_angle_deg': 'Wing Angle'},
                 opacity=0.4)

fig.show()

In [47]:
#when the speed increases the drag increases alongside with it, and the angle of the spoiler causes the drag to increase too

In [48]:
import plotly.express as px

# Using a sample of the data for performance
sample_df = df_sorted_asc.sample(n=min(20000, len(df_sorted_asc)))

# Ensure drs_active is treated as a categorical variable for the graph
sample_df['drs_active'] = sample_df['drs_active'].astype(str)

# Create a scatter plot comparing DRS states
fig = px.scatter(sample_df,
                 x='speed_kmh',
                 y='stability_index',
                 color='drs_active',
                 title='Stability Index vs Speed: DRS OFF (0) vs DRS ON (1)',
                 labels={'speed_kmh': 'Speed (km/h)', 'stability_index': 'Stability Index', 'drs_active': 'DRS Status'},
                 opacity=0.4,
                 color_discrete_map={'0': 'blue', '1': 'orange'})

fig.show()

In [49]:
import pandas as pd
from scipy import stats

# Calculate correlation between drs_active and stability_index
# Point-biserial correlation is used for one binary and one continuous variable
correlation, p_value = stats.pointbiserialr(df_sorted_asc['drs_active'], df_sorted_asc['stability_index'])

print(f"Correlation Coefficient: {correlation:.4f}")
print(f"P-value: {p_value:.4e}")

# Grouped mean for context
grouped_means = df_sorted_asc.groupby('drs_active')['stability_index'].mean()
print("\nAverage Stability Index by DRS Status:")
print(grouped_means)

Correlation Coefficient: 0.0011
P-value: 6.7855e-01

Average Stability Index by DRS Status:
drs_active
0    91.316133
1    91.374038
Name: stability_index, dtype: float64

In [50]:
#DRS has no connection with the stability of the car

In [51]:
def calculate_stability_threshold(df):
    """
    let's take the maximum downforce number that can be recorded without braking the stability
    of the car.
    """
    # Identify the first row where stability is no longer perfect (100)
    instability_point = df[df['stability_index'] < 100].head(1)

    if instability_point.empty:
        return "No instability detected in the current dataset.", None

    threshold_n = instability_point['downforce_n'].values[0]
    speed_at_limit = instability_point['speed_kmh'].values[0]
    wing_at_limit = instability_point['wing_angle_deg'].values[0]

    return threshold_n, {
        'speed': speed_at_limit,
        'wing_angle': wing_at_limit,
        'stability': instability_point['stability_index'].values[0]
    }

# Execute calculation
limit_n, details = calculate_stability_threshold(df_sorted_asc)

if details:
    print("--- Downforce Stability Threshold Platform ---")
    print(f"Maximum Safe Downforce Limit: {limit_n:.2f} N")
    print(f"Critical Speed reached: {details['speed']:.2f} km/h")
    print(f"Critical Wing Angle: {details['wing_angle']:.2f} deg")
    print(f"Initial Stability Drop: {details['stability']:.2f}%")

    # Apply flagging to the dataset for further analysis
    df_sorted_asc['stability_status'] = df_sorted_asc['downforce_n'].apply(
        lambda x: 'SAFE' if x < limit_n else 'STABILITY_WARNING'
    )
else:
    print(limit_n)

--- Downforce Stability Threshold Platform ---
Maximum Safe Downforce Limit: 4504.30 N
Critical Speed reached: 258.30 km/h
Critical Wing Angle: 34.85 deg
Initial Stability Drop: 99.78%